### ISSUE TITLE
Start in Github steps for contribute to this project.

### ISSUE THREAD

**Issue by caroline-rodrigues** [caroline-rodrigues/start_hacktoberfest2020#1]
Here are 3 quick and painless ways to contribute to this project:

Add your name to the CONTRIBUTORS.md file
Add a profile page to the profiles directory
Create a simple "Hello, World" script in a language of your choice
Choose one or all 3, make a pull request for your work, and wait for it to be merged!

**Comment by cl0ne** [comment]
https://hacktoberfest.digitalocean.com/details#spam
