### ISSUE TITLE
Hey my pull request merged but due to spamming can you add a label hacktoberfest accepted in my pull request.

### ISSUE THREAD

**Issue by siddharthdeo99** [caroline-rodrigues/start_hacktoberfest2020#66]
Hey @caroline-rodrigues 2 days earlier you have merged my  Hello world program in javascript and some modification in CONTRIBUTERS.md .But due to recent spamming on hacktoberfest 2020 some policy were changed so can you label my pull request to hacktoberfest accepted label? Any help would be appreciated.Thank you
#Hacktoberfest2020

**Comment by caroline-rodrigues** [comment]
Done! ;)
